### ISSUE TITLE
Upload to a specific Cloudinary folder?

### ISSUE THREAD

**Issue by theGreatAndPowerfulOz** [pcon/cloudinary-cli#1]
This is not an issue; just a question. Is there a way to specify a particular Cloudinary folder to upload to with this CLI? I don't see any documentation for that. Thanks!

**Comment by pcon** [comment]
There's not a way to do it with the CLI right now.  Give me a little bit and I'll see if I can update it to do so.  I don't think it'll be too complicated.  It'll also give me an excuse to update the version of the libraries

**Comment by pcon** [comment]
I was pretty easily able to get it to upload to a folder.  But.... when I wrote this 4 years ago I did a pretty bad job of using commander to make things run.  Because of that parameters are getting passed around like they should.  It's going to take me a day or two but I'm going to refactor it a little bit to make it work.

**Comment by theGreatAndPowerfulOz** [comment]
@pcon - I appreciate the effort!

**Comment by pcon** [comment]
This should be working now.  You'll need to update to `1.1.0` of the package and use the `-f` flag

```bash
cloudinary upload -f myfolder file.png
```

**Comment by theGreatAndPowerfulOz** [comment]
Thanks for the update, @pcon! I had not yet been using any version of the package (I was just hunting around for a Cloudinary CLI), but I'll grab `1.1.0` and give it a try. 👍

**Comment by osde8info** [comment]
> Thanks for the update, [@pcon](https://github.com/pcon)! I had not yet been using any version of the package (I was just hunting around for a Cloudinary CLI), but I'll grab `1.1.0` and give it a try. 👍

try pipx install cloudinary-cli
